services:
  - type: worker
    name: caixa-segredos-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TARGET_CHAT_ID
        sync: false
